/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.javafreedom.kotlin-library-conventions")
}

dependencies {
    testImplementation("com.willowtreeapps.assertk:assertk-jvm:0.23")
}