/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.javafreedom.app

object MessageUtils {
    const val MESSAGE = "Hello      World!"
    
    fun getMessage(): String = MESSAGE
}
