/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package org.javafreedom.utilities

import org.javafreedom.list.LinkedList
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class JoinUtilsTest {
    @Test
    fun testJoinEmptyList() {
        val list = LinkedList()
        assertEquals("", JoinUtils.join(list))
    }

    @Test
    fun testJoinSingleElement() {
        val list = LinkedList()
        list.add("Hello")
        assertEquals("Hello", JoinUtils.join(list))
    }

    @Test
    fun testJoinMultipleElements() {
        val list = LinkedList()
        list.add("Hello")
        list.add("World")
        list.add("!")
        assertEquals("Hello World !", JoinUtils.join(list))
    }

    @Test
    fun testJoinWithSpecialCharacters() {
        val list = LinkedList()
        list.add("@#$")
        list.add("123")
        list.add("abc")
        assertEquals("@#$ 123 abc", JoinUtils.join(list))
    }
}