name: CI Build

on: [push]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean classes testClasses testIntegrationClasses
          wrapper-cache-enabled: true

  tests:
    name: Tests
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean check sonarqube aggregateReports
          wrapper-cache-enabled: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload documentation results
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: build/documentation

  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check OWASP
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean dependencyCheckAnalyze
          wrapper-cache-enabled: true

  release:
    name: Release
    needs: [tests, security]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build package
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble -x test -x integrationTest
          wrapper-cache-enabled: true
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits @semantic-release/exec
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      revnumber: ${{ env.revnumber }}

  build-publish-docker:
    name: Build and Publish Docker Image
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build package
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean assemble dockerCreateDockerfile -x test -x integrationTest
          wrapper-cache-enabled: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/app/build/docker/
          file: ./modules/app/build/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/triplem/gradle-by-example:latest
            ghcr.io/triplem/gradle-by-example:${{ needs.release.outputs.revnumber }}

  publish-docs:
    name: Publish Docs
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download documentation reports
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: build/documentation
      - name: Build package
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateDocumentation
          wrapper-cache-enabled: true
        env:
          revnumber: ${{ needs.release.outputs.revnumber }}
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/documentation
          CLEAN: true